language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - 7.0

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0
    
before_script:
 - composer update

script:
  - vendor/bin/phpcs --standard=PSR2 src
  
  